homepageTabUI <- function(id)
{
  fluidRow(
    
    #includeHTML("www/index.html"),
    #includeCSS("www/homepage.css")
    
    
    tags$head(
      # Note the wrapping of the string in HTML()
      tags$style(HTML("
        .simple-background {
           height: 150px;
           width: 150px;
           background-image: url(food.jpg);
           background-size: cover;
           filter: blur(30px);
           transition: 100ms filter linear;
        }
        
        .background-image{
             background-image: url('food.jpg');
             background-size: cover;
             height:700px
            
        }
        
        .title{
            color: white;
            text-align:center;
        }
        
      "))),
    
    fluidRow(
      tags$div(class = "background-image",
               
               tags$h1("TARTARE Dashboard", class = "title"),
               #tags$h1("TARTARE Dashboard", style = "text-align:center; background-image: url('food.jpg');"),
            
               
               
      ),
      
      box(
        tags$h1("Features",),
        
        tags$h3("Hazard Graphs"),
        tags$p("The main functionality of the dashboard is the graphing features. There currently are five different graphs: All Hazards, All Hazards Test, FERG Hazards, Scatter Plot, and Weighted
               Scatter Plot."),
        
        tags$h3("Simulation"),
        tags$p("The dashboard provides many different ways to visualize exisiting TARTARE data. But what if a user wants to generate data on other diseases they have data for?
               And what if the user wants to compare the generated data with the TARTARE data? These capabilities are supported by the dashboard in the 'Add New Hazards' and 'All Hazards Test' tabs."),
        tags$br(),
        tags$h4(style="margin-left: 40px","Add New Hazards Tab"),
        tags$br(),
        tags$p(style="margin-left: 40px","This tab contains the simulation used to generate part of the All Hazard data. The simulation can be used the same way for other diseases provided by the user.
               The simulation requires a EXCEL or CSV file of the bounds of each disease, and returns a CSV file of 10,000 data points for each input disease."),
        
        tags$br(),
        
        tags$h4(style="margin-left: 40px","All Hazards Test Tab"),
        tags$br(),
        tags$p(style="margin-left: 40px","The data generated by the simulation can then be uploaded graphed in comparison to the TARTARE data."),
        tags$p(style="margin-left: 40px","NOTE: The current functionality is limited and is still under development"),
        
        width = 11, solidHeader = TRUE
      ),
      
      box(
        tags$h1("Contact Us"),
        
        tags$br(),
        fluidRow(
          
          box(
            tags$h3(style="text-align:center;", "Barbara Kowalcyk"),
            tags$br(),
            tags$br(),
            
            tags$p("Email: kowalcyk.1@osu.edu"),
            
            width = 4
          ),
          
          box(
            tags$h3(style="text-align:center;", "Arie Havelaar"),
            tags$br(),
            tags$br(),
            
            tags$p("Email: ariehavelaar@ufl.edu"),
            
            width = 4
          )
          
        ),
        
        
        width = 11
      )
      
    
    )
    # tags$div(
    #   <
    # 
    # 
    # 
    # 
    # )
    # 
    #   <div class="box-item">
    #   <i class="ti-vector"></i>
    #   <h6 class="box-title"> Graphing</h6>
    #   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis excepturi, repellat esse laborum explicabo quia.</p>
    #   </div>
    #   <div class="box-item">
    #   <i class="ti-filter"></i>
    #   <h6 class="box-title"> Simulation </h6>
    #   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis excepturi, repellat esse laborum explicabo quia.</p>
    #   </div>
    # </div>

  )
}


homepageTabServer <- function(id)
{
  moduleServer(id, function(input, output, session)
  {
   
  })
}