homepageTabUI <- function(id)
{
  fluidRow(
    
    #includeHTML("www/index.html"),
    #includeCSS("www/homepage.css")
    
    
    tags$head(
      # Note the wrapping of the string in HTML()
      tags$style(HTML("
        .simple-background {
           height: 150px;
           width: 150px;
           background-image: url('home_image.png');
           background-size: cover;
           filter: blur(30px);
           transition: 100ms filter linear;
        }
        
        .background-image{
             background-image: url('home_image.png');
             background-size: cover;
             height:1000px
            
        }
        
        .title{
            color: white;
            text-align:center;
        }
        
      "))),
    
    fluidRow(
      tags$div(class = "background-image",
               
               tags$h1("TARTARE Dashboard", class = "title"),
               #tags$h1("TARTARE Dashboard", style = "text-align:center; background-image: url('food.jpg');"),
               
      )),
    fluidRow(
      
      column(width=12, offset=0,
      box(
        tags$h1("OVERVIEW"),
        tags$p(style = "line-height:25px","Foodborne diseases are important public health problems in low- and middle-income countries, causing considerable morbidity and mortality and, thus, having a substantial social and economic impact. Yet, the burden of foodborne disease is not well understood in countries such as Ethiopia. 
        This dashboard presents burden estimates for selected foodborne hazards in Ethiopia using 2010 as a reference year. 
        It includes estimates developed by the World Health Organization Foodborne Disease Burden Epidemiology Reference Group (FERG) for Ethiopia, estimates generated for four metals, and estimates generated by the TARTARE project for hazards that were not estimated by FERG but were deemed important by Ethiopian food safety stakeholders. 
        Additional details on the methods used to derive these estimates can be found at <insert reference>.
        Users can view and interactively compare burden estimates for foodborne hazards several ways (i.e., boxplots, scatter plots) using different risk metrics:"), 
        
        tags$ul(
          tags$li("The ALL HAZARDS tab can be used to examine disease burden estimates for all considered hazards using a single metric."),
          tags$li("The FERG HAZARDS tab can be used to examine estimates for FERG hazards only using a single metric."),
          tags$li("The SCATTERPLOT tab can be used to examine estimates using two risk metrics."),
          tags$li("The WEIGHTED SCATTERPLOT tab can be used to examine disease burden estimates using three risk metrics. "),
          tags$li("The ADD NEW HAZARDS tab allows users to upload an EXCEL or CSV file to generate estimates (through simulation) for additional hazards.") 
          
        ),
        
        tags$p("The data dashboard was created using the R package shiny (Chang et al., 2023) and plots are generated using the R ggplot2 package (Wickham, 2016).  "),
    
        
        width = 11, solidHeader = TRUE
      ))),
      
    fluidRow(
      box(
        tags$h1("Contact Us"),
        
        tags$br(),
        fluidRow(
          
          box(
            tags$h3(style="text-align:center;", "Barbara Kowalcyk, PhD"),
            tags$p(style="text-align:center;","George Washington University"),
            tags$br(),
            
            tags$div(style="text-align:center;",
              tags$a("Barbara.kowalcyk@gwu.edu",
                     href = "Barbara.kowalcyk@gwu.edu"),
            ),
            width = 4,
          ),
          
          box(
            tags$h3(style="text-align:center;", "Arie Havelaar, PhD"),
            tags$p(style="text-align:center;","University of Florida"),
            tags$br(),
            
            tags$div(style="text-align:center;",
              tags$a("ariehavelaar@ufl.edu", 
                     href = "ariehavelaar@ufl.edu")
            ),
            
            width = 4
          )
          
        ),
        
        
        width = 11
      )
      
    
    )

  )
}


homepageTabServer <- function(id)
{
  moduleServer(id, function(input, output, session)
  {
   
  })
}